# The name of workflow. GitHub displays the names on repository's actions page. 
# If omitted, GitHub sets it to the workflow file path relative to the root of the repository.
# see: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Publish package to the Maven Central Repository

# Triggered when code is pushed to any branch in a repository
#on: push
# Triggers the workflow on push or pull request events
#on: [push, pull_request]
# Triggers on event release with type created
on:
  release:
    types: [created]
    
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$MY_VARIABLE_NAME"
        env:
          First_Name: Mona

  publish:
    runs-on: ubuntu-latest
	environment: staging
#    continue-on-error: ${{ matrix.experimental }}
#    strategy:
#      matrix:
#        java: [ 8, 11, 16 ]
#        experimental: [false]
#        include:
#          - java: 17-ea
#            experimental: true        
    strategy:
      matrix:
        java: [ 16 ]
        
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
#       run: mvn -V --batch-mode -Ddoclint=all --file pom.xml --no-transfer-progress deploy
        run: mvn -V --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
